In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr(1)

TypeError: 'numpy.ndarray' object is not callable

In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
arr(1)

TypeError: 'numpy.ndarray' object is not callable

In [12]:
#ROW INDEXING

arr[1]

array([4, 5, 6])

In [13]:
arr[1,]

array([4, 5, 6])

In [14]:
arr[1:2,]

array([[4, 5, 6]])

In [15]:
arr[1:2]

array([[4, 5, 6]])

In [ ]:
arr[]

In [16]:
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr[:1]

array([[1, 2, 3]])

In [19]:
arr[0:1]

array([[1, 2, 3]])

In [20]:
arr[1:1]

array([], shape=(0, 3), dtype=int32)

In [21]:
arr[1:0]

array([], shape=(0, 3), dtype=int32)

In [22]:
arr[,1]

SyntaxError: invalid syntax (2468986438.py, line 1)

In [23]:
arr[1]

array([4, 5, 6])

In [24]:
#COLUM INDEX

arr[,1:2]

SyntaxError: invalid syntax (1667993879.py, line 1)

In [25]:
arr[1:2,1:2]

array([[5]])

In [26]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [27]:
arr[2:3,1:3]

array([[8, 9]])

In [28]:
arr[1:2,2:2]

array([], shape=(1, 0), dtype=int32)

In [29]:
arr[1:2,1:3]

array([[5, 6]])

In [30]:
arr[1:2,2:3]

array([[6]])

In [31]:
arr[2:1,0:1]

array([], shape=(0, 1), dtype=int32)

In [32]:
arr[2:3,0:1]

array([[7]])

In [33]:
arr[2:3,2:3]

array([[9]])

In [34]:
arr[0:2,1:2]

array([[2],
       [5]])

In [37]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [38]:
[:-1]

SyntaxError: invalid syntax (1011342872.py, line 1)

In [39]:
arr[:-1]|

SyntaxError: invalid syntax (1391045616.py, line 1)

In [40]:
#eliminating the last row
arr[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#eliminate the first two rows
arr[-1:]

array([[7, 8, 9]])

In [42]:
#print all rows in revers order
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [48]:
a=np.arange(10,31)

In [49]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [51]:
a[5]

15

In [52]:
a[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [53]:
a[-1:]

array([30])

In [54]:
a[:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])