import numpy as np

In [2]:
a=np.random.rand(3,10)

In [4]:
a

array([[0.04718125, 0.6311137 , 0.54175314, 0.16617812],
       [0.83196415, 0.00405077, 0.90827483, 0.1944742 ],
       [0.19549181, 0.26541177, 0.35274655, 0.43976464]])

In [7]:
b=np.linspace(1,5)

In [8]:
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [9]:
a=np.random.rand(3)

In [10]:
a

array([0.24184536, 0.96674326, 0.96422434])

In [11]:
a=np.random.rand(2,3)

In [12]:
a

array([[0.50851823, 0.60300129, 0.70852775],
       [0.97496053, 0.27415426, 0.00352123]])

In [13]:
c=np.array([[2,4,6,8],[1,3,5,7],[10,11,12,13]])

In [14]:
c

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [10, 11, 12, 13]])

In [15]:
c[1]

array([1, 3, 5, 7])

In [16]:
c[0]

array([2, 4, 6, 8])

In [17]:
c[2:3]

array([[10, 11, 12, 13]])

In [18]:
c[1:3]

array([[ 1,  3,  5,  7],
       [10, 11, 12, 13]])

In [19]:
c[:2]

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [20]:
c[0:1,1:2]

array([[4]])

In [21]:
c[0,1]

4

In [22]:
c[1:3]

array([[ 1,  3,  5,  7],
       [10, 11, 12, 13]])

In [23]:
c[0:1,0:4]

array([[2, 4, 6, 8]])

In [24]:
c[0:3,1:4]

array([[ 4,  6,  8],
       [ 3,  5,  7],
       [11, 12, 13]])

In [25]:
c[1,-1]

7

In [26]:
c[1:2,2:3]

array([[5]])

In [27]:
c[:-1]

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [28]:
c[-1:]

array([[10, 11, 12, 13]])

In [29]:
c[::-1]

array([[10, 11, 12, 13],
       [ 1,  3,  5,  7],
       [ 2,  4,  6,  8]])