In [ ]:
 #operations in numpy

In [1]:
import numpy as np

In [8]:
# matrix multiplication:( dot product)  
a=np.array([[2,4],[1,3]])

In [9]:
a

array([[2, 4],
       [1, 3]])

In [11]:
b=np.array([[5,6],[8,9]])

In [12]:
b

array([[5, 6],
       [8, 9]])

In [14]:
#multiplication syntax
np.dot(a,b)

array([[42, 48],
       [29, 33]])

In [15]:
a+b

array([[ 7, 10],
       [ 9, 12]])

In [16]:
a-b

array([[-3, -2],
       [-7, -6]])

In [18]:
c=np.array([12,13])

In [19]:
d=np.array([21,22])

In [20]:
c+d

array([33, 35])

In [21]:
c*d

array([252, 286])

In [22]:
a*b

array([[10, 24],
       [ 8, 27]])

In [27]:
# incresing the protcast value for interview question
e=np.array([10,15])

In [26]:
c

array([12, 13])

In [28]:
c+e

array([22, 28])

In [29]:
#diff btw scaler and vector
#scalar= operation performed by using integers
#vectors= operation performed by using arrays

SyntaxError: invalid syntax (3049862118.py, line 2)

In [30]:
c+5

array([17, 18])

In [31]:
# stacking and splitting
# syntax:
     #np.vstack((a,b))
     #np.hstack((a,b))
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [32]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
# Numpy array functions
arr3=np.array([1,2,3,4,5,6,7,8,9])

In [35]:
np.array_split(arr3,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9, 0])]

In [36]:
arr3.size

10

In [37]:
arr3.dtype

dtype('int32')

In [38]:
np.log(arr3)

C:\Users\Surya\AppData\Local\Temp\ipykernel_12440\2430430252.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr3)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458,       -inf])

In [39]:
np.exp(arr3)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 1.00000000e+00])

In [40]:
np.mean(arr3)

4.5

In [41]:
np.median(arr3)

4.5

In [42]:
np.mode(arr3)

AttributeError: module 'numpy' has no attribute 'mode'

In [43]:
np.std(arr3)

2.8722813232690143

In [44]:
np.var(arr3)

8.25

In [45]:
np.prod(arr3)

0

In [46]:
np.prod(arr2)

1680

In [47]:
np.min(arr3)

0

In [48]:
np.max(arr3)

9

In [49]:
f=arr3+0.1

In [50]:
f

array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1, 0.1])

In [51]:
np.ceil(f)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  1.])

In [52]:
np.floor(f)

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0.])

In [53]:
a.T

array([[2, 1],
       [4, 3]])