In [1]:
import numpy as np

In [2]:
a=np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [3]:
a

NameError: name 'a' is not defined

In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
a=np.reshape(4,3)

ValueError: cannot reshape array of size 1 into shape (3,)

In [7]:
a.reshape(2)

ValueError: cannot reshape array of size 3 into shape (2,)

In [8]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a.reshape(2)

ValueError: cannot reshape array of size 10 into shape (2,)

In [11]:
a.reshape(4,-1)


ValueError: cannot reshape array of size 10 into shape (4,newaxis)

In [12]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b=np.array([2,4,6,8,10,12,14,16,18,20,22,24])

In [14]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [15]:
b.reshape(4,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [16]:
b.reshape(4,-1)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [17]:
b.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)